steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - hello_gcp1
  - --source=.
  - --trigger-http
  - --runtime=python37
  - --allow-unauthenticated
  - --service-account=662469587140@cloudbuild.gserviceaccount.com


